# 場景設置
[[scenes]]
id = "universal"
background = "assets/universal.png"
description = "環球影城場景"

[[scenes]]
id = "home"
background = "assets/home.png"
description = "這是家的場景"

[[scenes]]
id = "popcorn_shop"
background = "assets/popcorn_shop.png"
description = "這是爆米花攤販的場景。"

[[scenes]]
id = "cinema"
background = "assets/cinema_bg.png"
description = "這是電影院的場景。"

[[scenes]]
id = "MRT"
background = "assets/MRT_bg.png"
description = "這是MRT的場景。"

[[scenes]]
id = "universal_gate"
background = "assets/universal_gate.png"
description = "這是環球影城門口的場景。"

[[scenes]]
id = "little_yellow"
background = "assets/little_yellow.png"
description = "這是小小兵的場景。"

[[scenes]]
id = "mario"
background = "assets/mario.png"
description = "這是Mario的場景。"

[[scenes]]
id = "hogwarts"
background = "assets/hogwarts.png"
description = "這是Hogwarts的場景。"

# 人物設置
[[characters]]
id = "shido"
name = "五河士道"
avatar = "assets/shido_avatar.png"
sprite = "assets/shido_sprite.png"
affection = 50  # 士道的初始好感度

[[characters]]
id = "tohka"
name = "夜刀神十香"
avatar = "assets/tohka_avatar.png"
sprite = "assets/tohka_sprite.png"
affection = 50  # 十香的初始好感度

[[characters]]
id = "kurumi"
name = "時崎狂三"
avatar = "assets/kurumi_avatar.png"
sprite = "assets/kurumi_sprite.png"
affection = 50  # 狂三的初始好感度

# 物品設置
[[items]]
id = "popcorn_bucket"
name = "爆米花桶"
icon = "assets/popcorn_bucket_icon.png"

[[items]]
id = "date_ticket"
name = "約會券"
icon = "assets/date_ticket_icon.png"

[[items]]
id = "money"
name = "千元大鈔"
icon = "assets/money_icon.png"
quality = 5

[[items]]
id = "souvenir"
name = "紀念品"
icon = "assets/souvenir_icon.png"

# 劇情設置
[[events]]
scene = "home"
character = "shido"
dialogue = "你們今天想要去環球影城玩嗎?"
choices = [
    { text = "環球影城", next_event = "to_universal" },
    { text = "不要，環球影城這麼無聊。", next_event = "no_universal" },
    { text = "什麼出去玩，我宅男在家睡。", next_event = "sleep_ending" } #還沒寫
]

[[events]]
id = "to_universal"
scene = "home"
character = "shido"
dialogue = "那我要怎麼過去嘞?"
choices = [
    { text = "搭大眾運輸工具", next_event = "MRT_to_universal"},
    { text = "自己開車", next_event = "drive_to_universal"},
    { text = "搭乘計程車", next_event = "taxi_to_universal"}
]

[[events]]
id = "taxi_to_universal"
scene = "home"
character = 0
dialogue = "(搭乘計程車金錢數量-1)"
next_event = "arrive_universal"

[[events]]
id = "MRT_to_universal"
scene = "MRT"
character = "shido"
dialogue = "(捷運上面好擠啊，怎麼這麼多人想要去環球影城。)"
next_event = "MRT_to_universal2"

[[events]]
id = "MRT_to_universal2"
scene = "MRT"
character = "shido"
dialogue = "(難以想像等下的環球影城有多少人...)"
next_event = "arrive_universal"

[[events]]
id = "arrive_universal"
scene = "universal_gate"
character = "shido"
dialogue = "哇!入口處就這麼的華麗，好美麗啊!"
next_event = "find_kurumi"

[[events]]
id = "find_kurumi"
scene = "universal_gate"
character = "shido"
dialogue = "(那邊那個人看起來好像狂三喔!要去確認看看嗎?)"
choices = [
    { text = "直接去確認", next_event = "meet_kurumi_directly"},
    { text = "直接忽視", next_event = "avoid_kurumi_but_meet"},
    { text = "偷偷跟蹤到他的旁邊嚇她一跳", next_event = "meet_kurumi_scary"}
]

[[events]]
id = "meet_kurumi_directly"
scene = "universal_gate"
character = "shido"
dialogue = "狂三!是你嗎~你今天也來環球影城玩喔!"
next_event = "meet_kurumi_directly1"

[[events]]
id = "meet_kurumi_directly1"
scene = "universal_gate"
character = "kurumi"
dialogue = "對呀，居然能在這碰到你，真的是好巧阿!這麼巧的話那要不我們一起玩?"
choices = [
    { text = "毫不猶豫就說好啊!", next_event = "meet_kurumi_directly"},
    { text = "思考個10秒才說好", next_event = "avoid_kurumi_but_meet"},
    { text = "...", next_event = "meet_kurumi_scary"}
]

[[events]]
id = "meet_kurumi_scary"
scene = "universal_gate"
character = "kurumi"
dialogue = "啊!!!，原來是士道啊，突然出現嚇我一跳，你今天也來環球嗎!這麼巧的話那要不我們一起玩?"
choices = [
    { text = "毫不猶豫就說好啊!", next_event = "yes_fast", affection_changes = { character = "kurumi", change = 5 }},
    { text = "思考個10秒才說好", next_event = "yes_long", affection_changes = { character = "kurumi", change = -5 }},
    { text = "...", next_event = "noreaction", affection_changes = { character = "kurumi", change = -5 }}
]

[[events]]
id = "avoid_kurumi_but_meet"
scene = "universal"
character = "kurumi"
dialogue = "哦？士道!真巧啊，你今天也來環球影城呀!我剛剛明明就看到你看到我，居然直接忽視啊..."
next_event = "continue_universal_with_kurumi"

[[events]]
id = "continue_universal_with_kurumi"
scene = "universal"
character = "shido"
dialogue = "那我們應該要先去哪裡玩呢?"
next_event = "tohka_choose"

[[events]]
id = "tohka_choose"
scene = "universal"
character = "tohka"
dialogue = "我想要先去小小兵主題遊樂區，小小兵們都好可愛!"
next_event = "kurumi_choose"

[[events]]
id = "kurumi_choose"
scene = "universal"
character = "kurumi"
dialogue = "可是我想要去超級任天堂世界耶，士道你覺得哩?"
choices = [
    { text = "去小小兵主題遊樂區", next_event = "little_yellow", affection_changes = [{ character = "kurumi", change = -5 }, { character = "tohka", change = 5 }] },
    { text = "去超級任天堂世界", next_event = "mario", affection_changes = [{ character = "kurumi", change = 5 }, { character = "tohka", change = -5 }] },
    { text = "那我們去哈利波特的魔法世界吧!", next_event = "hogwarts", affection_changes = [{ character = "kurumi", change = -5 }, { character = "tohka", change = -5 }] }
]

[[events]]
id = "little_yellow"
scene = "little_yellow"
character = "tohka"
dialogue = "小小兵的佈景做的好美阿~"
next_event = "kurumi_little_yellow"

[[events]]
id = "kurumi_little_yellow"
scene = "little_yellow_"
character = "kunumi"
dialogue = "每個地方都做得好精緻，連我不怎喜歡小小兵的人都覺得好美~"
next_event = "tohka_little_yellow"

[[events]]
id = "kunumi_little_yellow"
scene = "little_yellow"
character = "kunumi"
dialogue = "我們要不要去玩那個小小兵的遊樂設施?"
next_event = "yellow_play_tohka"

[[events]]
id = "yellow_play_tohka"
scene = "little_yellow"
character = "tohka"
dialogue = "蛤~可是我想要先去吃飯，士道你覺得哩?"
choices = [
    { text = "先去吃飯", next_event = "yellow_eat", affection_changes = [{ character = "kurumi", change = -5 }, { character = "tohka", change = 5 }] },
    { text = "先去玩遊樂設施", next_event = "yellow_play", affection_changes = [{ character = "kurumi", change = 5 }, { character = "tohka", change = -5 }] },
    { text = "直接離開小小兵遊樂園區", next_event = "hogwarts", affection_changes = [{ character = "kurumi", change = -5 }, { character = "tohka", change = -5 }] }
]